---
- name: Install and Configure Software
  hosts: hostinger
  remote_user: root

  vars:
    - docker_compose_version: "1.29.2"

  tasks:
    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Docker Engine
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "u+x,g+x"

    - name: Add User to Docker Group
      user:
        name: "{{ ansible_user }}"
        groups: docker

    - name: Set Permissions for Docker Socket
      file:
        path: /var/run/docker.sock
        mode: "660"
        owner: root
        group: docker

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Fail2ban
      apt:
        name: fail2ban
        state: present

    - name: Enable Fail2ban
      service:
        name: fail2ban
        state: started

  handlers:
    - name: Restart FirewallD
      service:
        name: firewalld
        state: restarted

    - name: Restart Fail2ban
      service:
        name: fail2ban
        state: restarted
